name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build
      env:
        CI: false

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PCW-Configurator-${{ matrix.os }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/PCW-Configurator-ubuntu-latest/*
          artifacts/PCW-Configurator-macos-latest/*
          artifacts/PCW-Configurator-windows-latest/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}